# Generated by Django 5.2.15 on 2026-08-16

import django.db.models.deletion
import plane.db.models.integration.calendar
import uuid
from django.conf import settings
from django.db import migrations, models


def create_google_calendar_integration(apps, schema_editor):
    Integration = apps.get_model("db", "Integration")
    Integration.objects.get_or_create(
        provider="google_calendar",
        defaults={
            "title": "Google Calendar",
            "network": 1,
            "description": {
                "description": "Connect workspace members to Google Calendar.",
            },
            "author": "Plane",
            "verified": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0122_alter_draftissue_assignees_alter_issue_assignees_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspaceintegration",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="integrations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workspaceintegration",
            name="api_token",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="integrations",
                to="db.apitoken",
            ),
        ),
        migrations.CreateModel(
            name="GoogleCalendarConnection",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Modified At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Deleted At"),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("provider_account_id", models.CharField(blank=True, max_length=255)),
                ("provider_email", models.EmailField(blank=True, max_length=254)),
                (
                    "access_token",
                    plane.db.models.integration.calendar.EncryptedTextField(blank=True),
                ),
                (
                    "refresh_token",
                    plane.db.models.integration.calendar.EncryptedTextField(blank=True),
                ),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("scopes", models.JSONField(blank=True, default=list)),
                (
                    "desired_state",
                    models.CharField(
                        choices=[("disconnected", "Disconnected"), ("connected", "Connected")],
                        default="disconnected",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("disconnected", "Disconnected"),
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("error", "Error"),
                            ("cleanup_pending", "Cleanup pending"),
                        ],
                        default="disconnected",
                        max_length=32,
                    ),
                ),
                ("lifecycle_generation", models.PositiveBigIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("oauth_state", models.CharField(blank=True, max_length=255)),
                ("oauth_code_verifier", models.TextField(blank=True)),
                ("oauth_redirect_uri", models.TextField(blank=True)),
                ("oauth_attempt_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_calendar_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace_integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_calendar_connections",
                        to="db.workspaceintegration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Google Calendar Connection",
                "verbose_name_plural": "Google Calendar Connections",
                "db_table": "google_calendar_connections",
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace_integration", "member"),
                        name="google_calendar_connection_unique_member",
                    )
                ],
            },
        ),
        migrations.RunPython(create_google_calendar_integration, migrations.RunPython.noop),
    ]
