# Generated by Django 5.2.15 on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0123_google_calendar_integration"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlecalendarconnection",
            name="calendar_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
