# Generated by Django 5.2.15 on 2026-08-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0124_google_calendar_connection_calendar_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlecalendarconnection",
            name="calendar_operation_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
