# Generated by Django 5.2.15 on 2026-08-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0125_google_calendar_operation_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlecalendarconnection",
            name="retain_grant_after_cleanup",
            field=models.BooleanField(default=False),
        ),
    ]
