# Generated by Django 5.2.15 on 2026-08-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0126_google_calendar_cleanup_intent"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlecalendarconnection",
            name="last_success_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
