# Generated by Django 5.2.15 on 2026-08-23 20:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0127_google_calendar_connection_last_success_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleCalendarEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(choices=[("work_item", "Work item"), ("cycle", "Cycle")], max_length=32),
                ),
                ("entity_id", models.UUIDField()),
                ("google_event_id", models.CharField(max_length=1024)),
                ("payload_hash", models.CharField(max_length=64)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="db.googlecalendarconnection",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Google Calendar Event",
                "verbose_name_plural": "Google Calendar Events",
                "db_table": "google_calendar_events",
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("connection", "entity_type", "entity_id"), name="google_calendar_event_unique_entity"
                    ),
                    models.UniqueConstraint(
                        fields=("connection", "google_event_id"), name="google_calendar_event_unique_google_event"
                    ),
                ],
            },
        ),
    ]
