# Generated by Django 5.2.15 on 2026-08-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0128_google_calendar_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="google_calendar_sync_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
