# Generated by Django 5.2.15 on 2026-08-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0131_google_calendar_reconciliation_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlecalendarconnection",
            name="broken_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
