# Generated by Django 5.2.15 on 2026-08-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0132_google_calendar_broken_notice"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlecalendarconnection",
            name="broken_email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
